spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 8089

mybatis:
  mapper-locations: classpath:com/zyh/mapper/*.xml  #指定mapper配置文件位置
  type-aliases-package: com.zyh.entity              #指定起别名所在包